### ISSUE TITLE
v3.x: import/named cannot find types and interface when exports is used in package.json

### ISSUE THREAD

**Issue by amikheychik** [import-js/eslint-import-resolver-typescript#149]
After migration from v2.x to v3, the `import/named` rules started failing when I import a type or an interface. It does work when I switch to `import type`.

If I have a configuration like this in my `package.json`:

```
    "name": "@example/core",
    "exports": {
        ".": {
            "import": "./index.js",
            "require": "./index.cjs"
        },
        "./testing": {
            "import": "./testing/index.js",
            "require": "./testing/index.cjs"
        },
```

and `index.d.ts` file:

```
export declare type Example = unknown;
```

then I get an `import/named` error for code like:

```
import { Example } from `@example/core`;
```

but not 

```
import type { Example } from '@example/core`;
```

Same would be for imports from `@example/core/testing`.

I was able to fix it by adding `"types": "./index.d.ts` into the `exports` list.

This configuration does work:

```
    "exports": {
        ".": {
            "types": "./index.d.ts",
            "import": "./index.js",
            "require": "./index.cjs"
        },
        "./testing": {
            "types": "./testing/index.d.ts",
            "import": "./testing/index.js",
            "require": "./testing/index.cjs"
        },
```

This is an issue only starting v3.0.0. It works fine in v2.7.1.

The expected behavior is to default the declaration file to `index.d.ts` if it is not set explicitly.

**Comment by JounQin** [comment]
This is expected and match the spec.

**Comment by amikheychik** [comment]
Can you provide a link to the spec?

**Comment by JounQin** [comment]
> Can you provide a link to the spec?

@amikheychik See https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing

**Comment by amikheychik** [comment]
@JounQin thank you, but this is TypeScript 4.7. The error is happening on TS 4.6.

**Comment by JounQin** [comment]
We don't want to support such difference between versions, you can pin to `v2` if you can't upgrade to TypeScript 4.7 yet.

**Comment by amikheychik** [comment]
Then you have to add `"typescript": "^4.7.0"` as a peer dependency, so it is not possible to use the v3.x without it.

**Comment by JounQin** [comment]
> Then you have to add `"typescript": "^4.7.0"` as a peer dependency, so it is not possible to use the v3.x without it.

Good idea, and PR welcome.

**Comment by amikheychik** [comment]
@JounQin there is still a bug as the order of the properties somehow affects the result.

This `exports` works:

``` 
"./testing": {
  "types": "./testing/index.d.ts",
  "import": "./testing/index.js",
  "require": "./testing/index.cjs"
},
```

But the following are failing:

``` 
"./testing": {
  "import": "./testing/index.js",
  "types": "./testing/index.d.ts",
  "require": "./testing/index.cjs"
},
```

``` 
"./testing": {
  "import": "./testing/index.js",
  "require": "./testing/index.cjs",
  "types": "./testing/index.d.ts"
},
```

I've checked the link that you referenced, it does not specify that the `types` must be the first field.

Also, it does not actually require for types to be declared at all:

_**By default**, TypeScript overlays the same rules with import conditions – if you write an import from an ES module, it will look up the import field, and from a CommonJS module, it will look at the require field. **If it finds them, it will look for a corresponding declaration file**. If you need **to point to a different location** for your type declarations, you can **add a "types" import condition**._

**Comment by JounQin** [comment]
It’s also how is the the ESM spec work, typescript supports different `moduleResolution` options, but I’m not interested to supporting all of them, please just follow how ESM works.

See also https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

Please pin to `v2` if you can’t upgrade.

**Comment by JounQin** [comment]
But if you want to support them strongly, you can raise a PR for it, and I’ll review it then.

**Comment by JounQin** [comment]
I just forgot there was an option `conditionNames` actually, the default value is

https://github.com/import-js/eslint-import-resolver-typescript/blob/34a84c9b08b5a3b29e72b6947ff2004408dd081a/src/index.ts#L58-L66

You can just override the value you preferred, but the default value is how the spec works, so that won’t never change.
